<a href="https://colab.research.google.com/github/Gizasinasci86/Estudos_NumPy/blob/main/Estudo_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importar a biblioteca NumPy**

In [5]:
import numpy as np

In [4]:
#Gerar um NDArray de 2x3 (duas listas com 3 elementos).

dados=np.random.rand(2,3)

In [6]:
#Com o comando descrito no código acima, criamos duas listas contendo três elementos (com valores aleatórios) em cada uma delas.

dados

array([[0.12160698, 0.28313393, 0.80154276],
       [0.05584035, 0.47899717, 0.20235558]])

In [7]:
#Mostrar o tipo de Array que foi criado utilizando "dtype"

dados.dtype

dtype('float64')

In [8]:
#Vendo o tamanho e a quantidade de dimensões utilizando "shape":

dados.shape

(2, 3)

In [9]:
#Também é possível verificar a quantidade de dimensões utilizando o "ndim":

dados.ndim

2

In [10]:
#Criando ndarray usando a função array. Ao criar o array a função array tenta utilizar o melhor tipo de dado:

lista=[1,2,5,7.8,1.25]

#A lista acima é uma estrutura do Python. Agora vamos criar uma ndarray, que é uma estrutura do NumPy:

dados2=np.array(lista)

dados2

#Ao executar o código, é criado um ndarray e automaticamente ele transforma todos os elementos em tipo float porque alguns elementos deste tipo já estavam na lista.

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [11]:
#Utilizando uma segunda lista e um pouco diferente que na linguagem Python, significa lista com duas dimensões:

lista2=[[1,2,3,4],[4,3,2,1]]

In [12]:
dados3=np.array(lista2)
dados3

#Foi gerado um array com duas dimensões e somente com elementos tipo int.

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [15]:
#Se em uma das listas tiver um elemento tipo float, o nparray gerado terá todos os elementos transformados em float:

lista2_1=[[1.5,2,10,5],[6,12,15,40]]

dados3_1=np.array(lista2_1)

dados3_1

array([[ 1.5,  2. , 10. ,  5. ],
       [ 6. , 12. , 15. , 40. ]])

# **Outras maneiras de criar Array**

In [18]:
#Criar um Array com valores específicos. Ex: criar um conjunto de dados com 10 elemesntos "zero(0")"

dadoszero=np.zeros(10)

dadoszero


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
#Utilizando a mesma função anterior, mas agora em duas dimensões:

dadoszero2=np.zeros((2,3))

dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
dadoszero2_1=np.zeros((6,6))

dadoszero2_1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
dadoszero2_2=np.zeros((20,10))

dadoszero2_2


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
#Podemos também criar um array com elementos de valor "um(1)"?

dadosum=np.ones(5)

dadosum


array([1., 1., 1., 1., 1.])

In [25]:
#Criando dados sequenciais:

dadosseq=np.arange(10)

dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#Dados sequenciais com array de sequência de 0 a 20, de 2 em 2 :

dadosseq2=np.arange(0,20,2)

dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
dadosseq2.dtype

dtype('int64')

In [29]:
#Podemos transformar/converter os tipos dos elementos. Ex: int em float.

dadosseqf=dadosseq.astype(np.float64)

dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
dadosseqf.dtype

dtype('float64')

**A função "astype" é bastante utilizada na hora de tratar os dados. Sempre haverá a necessidade de realizar essas transformações.**

# **Aritmética com Arrays**

In [32]:
dados4=np.array([[1,2,3],[4,5,6]])

dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
#Realizando uma multiplicação entre os elementos dos dados4:

dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [34]:
#Realizando uma soma entre os elementos dos dados4:

dados4+dados4

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [36]:
#Realizando uma subtração entre os elementos dos dados4:

dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
#Realizando uma divisão entre os elementos dos dados4:

dados4/dados4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
#Podemos realizar as operações aritméticas dos elementos dos dados com outros números:

1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [50]:
#Podemos gerar um novo Array utilizando o resultado da operação aritmética:

dados5=dados4+dados4

dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [51]:
#Os dados4 permanece sendo o mesmo pois os dados5 foi criado como sendo outro conjunto de dados:

dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
#Podemos realizar comparações entre os conjuntos de dados:

dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

In [53]:
dados5<dados4

array([[False, False, False],
       [False, False, False]])

# **Indexação**

In [54]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
dadosseq[5]

5

Obs.: Diferente da lista em Python, um recorte (uma fatia de dado) de um ndarray, sofrerá um **broadcast**, é como se fosse um **view** de banco de dados. Ou seja, conforme mudamos os dados dessa fatia, os dados originais também serão alterados.

In [56]:
#Escolhendo uma sequência dentro da sequência original. No exemplo a seguir, o elemento que estiver na 6ª posição, não fará parte da sequência desejada. O número 6 significa que a escolha pára na 6ª posição, mas o elemento que está nesta posição, não será incluído na resposta final da sequência escolhida.

dadosseq[3:6]

array([3, 4, 5])

In [58]:
#Podemos acrescentar elementos em uma sequência específica. Ex:

dadosseq[3:6]=20

dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [59]:
#Podemos criar uma fatia de dados (aqui foram selecionados os elementos que estão nas posições 2 e 3):

fatiadados=dadosseq[2:4]

fatiadados

array([ 2, 20])

In [60]:
#Podemos acrescentar um valor na fatia do dados (lembrando que será acrescentado na sequência original de onde retiramos essa fatia):

fatiadados[1]=2000

fatiadados

array([   2, 2000])

In [61]:
#Comprovando o broadcast, o valor 2000 acrescentado na fatiadados, também foi incluído na dadosseq original:

dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [62]:
#Podemos pegar a fatiadados e atribuir um elemento em todas as posições:

fatiadados[:]=333

#Visualizando na dadosseq (sequência original), o valor "333" aparecerá nas posições selecionadas:

dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

#**Copiar dados**

In [63]:
fatia2=dadosseq[2:4].copy()

fatia2

array([333, 333])

In [65]:
#Posso alterar os valores desses elementos na cópia:

fatia2[:]=111
fatia2

array([111, 111])

In [66]:
#Porém, agora, os alementos no dadosseq não serão alterados, porque estamos trabalhando em uma cópia e não mexendo direto no conjunto de dados original.

dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

#**Array com mais de uma dimensão**

A ideia é a mesma em relação ao array de uma dimensão.

In [67]:
dados6=np.array([[1,2,3],[4,5,6],[7,8,9]])

dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
#A identificação da posição do elemento é igual às Matrizes, em Matemática (linha, coluna). Apenas não pode esquecer que a contagem começa na posição "zero", tanto para a identificação na linha quanto na coluna:

dados6[1,2]

#Neste exemplo, estamos identificando o elemento que está na segunda linha e na terceira coluna.

6

#**Máscaras**

In [70]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [71]:
mascara=(dadosseq<100)
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [72]:
#Podemos fazer uma comparação e ainda substituir tais elementos por outros valores:

dadosseq[dadosseq<20]=8888
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888, 8888, 8888, 8888])

#**Transposição**

In [73]:
dados7=np.arange(15).reshape((3,5))
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [74]:
#Transposição: o que era linha vira coluna e vice-versa.

dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#**Multiplicação de Matrizes com Dots**

In [75]:
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

Importante observar que na função transposição não há mudança de valores, apenas a mudança na localização das posições em relação às linhas e colunas de uma Matriz.

Existem muitas outras funções para serem exploradas, como: **sin, cos, power, mod, sqrt, entre outros.**